services:
    auth_service:
        build:
            context: ./microservices/auth-service
            dockerfile: Dockerfile.authservice
        container_name: auth_service
        ports:
            - "8001:8001"
        env_file:
            - .env
        volumes:
            - ./microservices/auth-service:/app
        restart: always
        depends_on:
            postgres:
                condition: service_healthy
        healthcheck:
            test: ["CMD-SHELL", "curl -f http://localhost:8001/api/auth/health/ || exit 1"]
            interval: 10s
            timeout: 10s
            retries: 5
    
    postgres:
        image: postgres:latest
        restart: always
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
            interval: 5s
            timeout: 5s
            retries: 5
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh

    adminer:
        image: adminer
        restart: always
        ports:
            - "8080:8080"

volumes:
    db_data:
